#!/usr/bin/env python
import argparse
from subprocess import check_call

parser = argparse.ArgumentParser(description='build command')
parser.add_argument('cmd', help='the command that will be executed.')
parser.add_argument('target', help='target for the command')

args = parser.parse_args()

from sys import platform as _platform
if _platform == 'linux' or _platform == 'linux2':
    # linux
    BROSWER = 'chrome'
elif _platform == 'darwin':
    # OS X
    BROSWER = 'open -a Google\ Chrome'
else:
    raise Exception('unsupported systems')

BLAZE_BASE = 'blaze-output/'

if args.cmd == 'test':
    check_call(['nosetests', args.target])
elif args.cmd == 'coverage':
    COVERAGE_DIR = BLAZE_BASE + args.target + '/coverage_html_output/'
    check_call(['nosetests', args.target, '--with-coverage',
                '--cover-html', '--cover-html-dir', COVERAGE_DIR])
    check_call(BROSWER + ' ' + COVERAGE_DIR + 'index.html', shell=True)
elif args.cmd == 'run':
    BLAZE_TARGET = args.target.replace('/', '.').replace('.py', '')
    check_call(['python', '-m', BLAZE_TARGET])
else:
    raise Exception('unknown blaze command')

