#!/usr/bin/env python
import argparse
import subprocess
import os
import sys

parser = argparse.ArgumentParser(description='build command')
parser.add_argument('cmd', help='the command that will be executed.')
parser.add_argument('target', help='target for the command')

args = parser.parse_args()

PYBRAIN_PATH = os.getcwd() + '/pybrain'
NOSE_BIN = 'nosetests'

MY_ENV = os.environ.copy()
MY_ENV['PYTHONPATH'] = PYBRAIN_PATH + ":" + MY_ENV.get('PYTHONPATH', '')

def run_cmds(cmds):
    for cmd in cmds:
        print '--> ', cmd
        p = subprocess.Popen(cmd, env=MY_ENV, shell=True)
        p.wait()

from sys import platform as _platform
if _platform == 'linux' or _platform == 'linux2':
    # linux
    BROSWER = 'chrome'
elif _platform == 'darwin':
    # OS X
    BROSWER = 'open -a Google\ Chrome'
else:
    raise Exception('unsupported systems')

BLAZE_BASE = 'blaze-output/'

cmds = []
if args.cmd == 'test':
    cmds.append('%s %s' % (NOSE_BIN, args.target))
elif args.cmd == 'coverage':
    COVERAGE_DIR = BLAZE_BASE + args.target + '/coverage_html_output/'
    NOSE_COVERAGE_CMD = ('%s %s --with-coverage --cover-html --cover-html-dir %s' %
                        (NOSE_BIN, args.target, COVERAGE_DIR))
    cmds.append(NOSE_COVERAGE_CMD)
    NOSE_VIEW_CMD = '%s %s/index.html' % (BROSWER, COVERAGE_DIR)
    cmds.append(NOSE_VIEW_CMD)
elif args.cmd == 'run':
    #  BLAZE_TARGET = args.target.replace('/', '.').replace('.py', '')
    #  cmds.append('python -m %s' % (BLAZE_TARGET))
    cmds.append('python %s' % (args.target))
else:
    raise Exception('unknown blaze command')

run_cmds(cmds)

